#!/usr/bin/env bash
# Build gitignored .env for local dev from Keychain (+ safe defaults).
# Never commit .env
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="$ROOT/.env"
ACCT="${USER}"

kc() {
  security find-generic-password -a "$ACCT" -s "$1" -w 2>/dev/null || true
}

AUTH=$(kc handyquote_auth_secret)
RESEND=$(kc resend_api_key)
DBPASS=$(kc handyquote_database_password)
R2_AK=$(kc handyquote_r2_access_key_id)
R2_SK=$(kc handyquote_r2_secret_access_key)
R2_ACCT=$(kc handyquote_r2_account_id)
R2_BUCKET=$(kc handyquote_r2_bucket)
R2_URL=$(kc handyquote_r2_public_url)

# Local DB default if no vaulted prod password
if [[ -z "$DBPASS" ]]; then
  DATABASE_URL='postgresql://postgres:postgres@localhost:5432/handyman_invoicing?schema=public'
else
  # Local docker postgres still uses local credentials; vaulted pass is for prod recovery
  DATABASE_URL='postgresql://postgres:postgres@localhost:5432/handyman_invoicing?schema=public'
fi

if [[ -z "$AUTH" ]]; then
  AUTH='dev-only-handyquote-secret-change-me'
fi

umask 077
cat > "$OUT" <<EOF
# Generated by scripts/secrets-write-local-env.sh — DO NOT COMMIT
APP_URL="http://localhost:3000"
NODE_ENV="development"
AUTH_SECRET="${AUTH}"
DATABASE_URL="${DATABASE_URL}"
PAYMENTS_MODE="mock"
ALLOW_MOCK_PAYMENTS="true"
EOF

if [[ -n "$RESEND" ]]; then
  {
    echo "RESEND_API_KEY=\"${RESEND}\""
    echo "RESEND_FROM_EMAIL=\"HandyQuote <onboarding@resend.dev>\""
  } >> "$OUT"
fi

if [[ -n "$R2_AK" && -n "$R2_SK" && -n "$R2_BUCKET" && -n "$R2_URL" ]]; then
  {
    echo "R2_ACCESS_KEY_ID=\"${R2_AK}\""
    echo "R2_SECRET_ACCESS_KEY=\"${R2_SK}\""
    echo "R2_BUCKET_NAME=\"${R2_BUCKET}\""
    echo "R2_PUBLIC_URL=\"${R2_URL}\""
    [[ -n "$R2_ACCT" ]] && echo "R2_ACCOUNT_ID=\"${R2_ACCT}\""
  } >> "$OUT"
fi

chmod 600 "$OUT"
echo "Wrote $OUT (mode 600). Keys present:"
grep -E '^[A-Z_]+=' "$OUT" | cut -d= -f1
